

export const AUTH_CALENDER_SUCCESS = "AUTH_CALENDER_SUCCESS"
export const AUTH_CALENDER_ERROR = "AUTH_CALENDER_ERROR"


export const GET_CALENDER_CREDENTIAL_SUCCESS = "GET_CALENDER_CREDENTIAL_SUCCESS"
export const GET_CALENDER_CREDENTIAL_ERROR = "GET_CALENDER_CREDENTIAL_ERROR"


export const SET_CALENDER_EVENT_SUCCESS = "SET_CALENDER_EVENT_SUCCESS"
export const SET_CALENDER_EVENT_FAILED = "SET_CALENDER_EVENT_FAILED"


export const GET_ALL_CALENDER_META_DATA_SUCCESS = "GET_ALL_CALENDER_META_DATA_SUCCESS"
export const GET_ALL_CALENDER_META_DATA_ERROR = "GET_ALL_CALENDER_META_DATA_ERROR"