export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED'

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'


export const USER_LOGIN_AUTH_SUCCESS = 'USER_LOGIN_AUTH_SUCCESS'
export const USER_LOGIN_AUTH_FAILED = 'USER_LOGIN_AUTH_FAILED'


export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAILED = 'GET_ALL_USER_FAILED'

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED'

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'


export const LOG_USER_SUCCESS = 'LOG_USER_SUCCESS'
export const LOG_USER_FAILED = 'LOG_USER_FAILED'


export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS'
export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR'


export const LOADIN_STATE = 'LOADING_STATE'
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE'